# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cafdd33323f684f7964e52d00c05203c53274a120b6eb48581b4173f2f01d2e994ab03860028d17d83af0117411635ef84a9536fa75d407cbd93756c0fe1b814

test:
  secret_key_base: 6750223de6cd16bd43715eda2a9b8f47382365775283f5ff64a56c8d46943506801ab7d84480a3367599795338b1e39059614d65db1f51d180cdc86d23aa7ddb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
